name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: himanshu24998
          outputs: |
            ./dist/github-contribution-grid-snake.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate snake animation"
          add: "dist"
